### PR TITLE
Added the ability to mark a single thread as read

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by acrobat** [comment]
Thanks @GrahamCampbell! Can you add a test for this endpoint and also a docs entry for it? Thanks!

**Comment by acrobat** [comment]
Thanks for the update @GrahamCampbell can you just add a docs entry and add this added endpoint to our changelog? Thanks!

**Comment by GrahamCampbell** [comment]
Going to hold of updating the change log, since I'd need to pull down the repo to my machine to do that, in order to rebase.

**Comment by GrahamCampbell** [comment]
Docs are updated, otherwise.

**Comment by acrobat** [comment]
Ok no problem, I will update them myself when preparing the release! Thanks @GrahamCampbell

**Pull request merged**
