### PR TITLE
Code Style

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Replaces #817.

### CODE REVIEW

**Comment by acrobat** [comment]
I wouldn't actually remove the php_cs config, but make it as close as possible to the styleci config. This will allow users to run php-cs-fixer locally before committing/creating a PR and actually have the code style correctly applied.

Styleci will catch the remaning issues and make sure PR's don't get merged with code style issues.

**Comment by GrahamCampbell** [comment]
I disagree with the sentiment of making contributors care about code style. StyleCI is there to automatically fix it for maintainers.

**Comment by kubawerlos** [comment]
@acrobat it's one way or another - PHP CS Fixer with it's config or relying on Style CI - having both is IMHO the worst solution.

> This will allow users to run php-cs-fixer locally before committing/creating a PR 

And that's why I prefer having PHP CS Fixer in the repo, so code style can be fixed before merging PR, not after.

**Comment by GrahamCampbell** [comment]
Ping.

**Comment by kubawerlos** [comment]
Pong.

What about the question above "ping"?

**Comment by GrahamCampbell** [comment]
I'm no longer able to edit this PR.

**Comment by GrahamCampbell** [comment]
And keeping the cache file ignored is fine. I don't think we should remove this, otherwise when someone does a git pull, they may accidentality commit the cache file.

**Comment by GrahamCampbell** [comment]
Ping @acrobat. :)

**Comment by acrobat** [comment]
Sorry I've lost track of this PR! Thanks @GrahamCampbell!

**Comment by kubawerlos** [comment]
@GrahamCampbell what should happen after the merge to fix the failing job https://github.styleci.io/analyses/YjOWdv?

**Comment by GrahamCampbell** [comment]
StyleCI sends over a PR to be merged. It looks like it was closed.

**Comment by GrahamCampbell** [comment]
https://github.com/KnpLabs/php-github-api/pull/840

**Pull request merged**
