### PR TITLE
Test

### PR DESCRIPTION
**Pull request by emersonthis**

### CODE REVIEW

**Comment by stof** [comment]
@emersonthis do you know you can use your fork of a composer package *without* renaming it ?

**Comment by GrahamCampbell** [comment]
Also, your branch name of `dev-master` is a bit strange since now you have `dev-dev-master`...

**Comment by emersonthis** [comment]
Hey thanks! I did learn that... The hard way! I misundertood the docs and changed the name in the composer.json wasn't working. This PR was accidental while trying to troubleshoot. Sorry. I'm planning to submit a real PR soon for using the new GitHub search API

**Comment by stof** [comment]
isn't it already supported in ``->search()`` ?

**Comment by emersonthis** [comment]
@stof last I checked only GitHub's "Legacy Search" parameters are supported. I filed [an issue](https://github.com/KnpLabs/php-github-api/issues/297), and I'd be happy to submit a PR for this.

**Comment by stof** [comment]
@emersonthis ``$client->search()`` (or ``$client->api('search')`` which is equivalent) is exposing the new search API since months: https://github.com/KnpLabs/php-github-api/blob/master/doc/search.md

**Comment by emersonthis** [comment]
Oops I totally missed that!

**Pull request closed without merging**
