### PR TITLE
CS: The body of each structure MUST be enclosed by braces. Braces should be properly placed. Body of braces should be properly indented.

### PR DESCRIPTION
**Pull request by keradus**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
That's quite a lot of cs pulls. it would have been better to ask what rules were wanted, then send one pull request.

**Comment by keradus** [comment]
Whole six.
This way one can not only choose rules in atomic way, but also read the diff. IMO it's better sending one big PR with too long diff.

**Comment by localheinz** [comment]
@keradus @GrahamCampbell 

:+1:

How about checking for CS violations on Travis as well? I mean, who doesn't love that?

**Comment by stof** [comment]
-1 for doing it on Travis itself. It is better to keep Travis failures for test failures only (easier to maintain). However, CS could be checked by Scrutinizer (and configuring it to mark the status as failed for CS violations). This way, the combined status would show that tests are passing but there is another issue.

**Comment by keradus** [comment]
I like Travis to do it a little more, it gives full control, like when sb want to check CS using PHP CS Fixer then in Travis he could also define a version of it, can't see that on Scrutinizer.
And love to do this by fabbot.io, but it's still beta.

One way or another this PR does not add running the checks anywhere, just fix the CS.

**Comment by GrahamCampbell** [comment]
@keradus https://styleci.io launches on tuesday. It uses php-cs-fixer under the hood. It'll be free for all. :)

**Comment by localheinz** [comment]
@GrahamCampbell 

Nice, looking forward to see this thing!

**Comment by keradus** [comment]
Cool ;)
12 lut 2015 19:03 "Graham Campbell" <notifications@github.com> napisał(a):

**Comment by pilot** [comment]
good :+1:

**Pull request merged**
