### PR TITLE
Make sure to add accept header

### LINKED ISSUE #411: Setting the api_version broken on master

### PR DESCRIPTION
**Pull request by Nyholm**
This PR makes sure we always add the Accept header. It does also make sure we add a new Accept header when we set the api_version option. 

This will fix #411

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This seems a little bit hacky tbh. It would be more desirable to seek a design that doesn't involve such messy state manipulation?

**Comment by Nyholm** [comment]
Do you have any suggestions? One could remove the `getOption` function completely and just have a `setVersion`.

**Comment by Nyholm** [comment]
`setOption` and `getOption` are removed.

**Comment by cursedcoder** [comment]
good job @Nyholm we will need to add a page about that in the docs

**Comment by Nyholm** [comment]
Thank you for merging.

**Pull request merged**
