### PR TITLE
Fixed phpdoc typo

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Can you just get StyleCI to fix up after? It has a setting which will auto-commit fixes after PRs are merged.

**Comment by Nyholm** [comment]
I know. But I have a bad "feeling" about auto-committing to master without a review. 
I updated your PR now

**Comment by GrahamCampbell** [comment]
It can also auto-send PRs and not merge them. :P

**Comment by acrobat** [comment]
Yeah I don't like "auto" fixing, it is for sure a nice feature. But we can just make each pr pass and we will be fine!

**Comment by GrahamCampbell** [comment]
ok, sure ;)

**Pull request merged**
