### PR TITLE
fix json schema to add/update gist comments

### PR DESCRIPTION
**Pull request by cmgmyr**
* added "body" for correct json schema to comply with https://developer.github.com/v3/gists/comments/
* updated tests

### CODE REVIEW

**Comment by cmgmyr** [comment]
Looks to be a timeout error with PHP 5.3.3 in Travis

**Comment by akovalyov** [comment]
I have restarted the build, let's see.

**Comment by cmgmyr** [comment]
Thanks, looking good now

**Comment by cursedcoder** [comment]
thanks @cmgmyr

**Pull request merged**
