### PR TITLE
Add support for SSO errors coming from the API

### PR DESCRIPTION
**Pull request by eiriksm**
Hello, thanks for this!

I just had a case where a token I used were throwing a runtimeexception because the org in question for the resource, had enforced SAML authentication. This was not something I could explicitly catch and do something with, so here is a PR fixing that.

Thanks again, keep up the good work!

### CODE REVIEW

**Comment by eiriksm** [comment]
As a reference, here are some docs referencing this header and how to use it:

https://developer.github.com/v3/auth/#authenticating-for-saml-sso

**Comment by acrobat** [comment]
Looks good @eiriksm! Can you apply the suggested changes from styleci and add a test for the new exception logic? Thanks!

**Comment by eiriksm** [comment]
Added a test and got styleCI passing :ship:

**Comment by acrobat** [comment]
Thanks @eiriksm! And congrats on your first contribution! 🎉

**Pull request merged**
