### PR TITLE
Update comment.md

### PR DESCRIPTION
**Pull request by MWCorentin**
At line 55 : change create by update

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you for the PR. Can you tell me why would you like to make this change?

**Comment by MWCorentin** [comment]
Because its not running when you use the word "create" at line 55, but if
you use "update" it run.

**Comment by GrahamCampbell** [comment]
That doesn't really explain anything?

**Comment by MWCorentin** [comment]
I wanted in my app update a comment connect to my githubs comment, then in
your file comments.md its specified to use the commande :
$client->api('issue')->comments()->create('KnpLabs', 'php-github-api',
33793831, array('body' ='my updated comment')); . This command is not
working but if i write this line :
$client->api('issue')->comments()->update('KnpLabs', 'php-github-api',
33793831, array('body' ='my updated comment')); it's working !

**Comment by Nyholm** [comment]
Thank you. 
You are correct. In the [current documentation](https://github.com/KnpLabs/php-github-api/blob/master/doc/issue/comments.md#update-a-comment-on-an-issue) under the heading "Update a comment" we have stated that you should run the code

```php
$client->api('issue')->comments()->create()
```

Which, of course, is wrong. 

👍

**Comment by MWCorentin** [comment]
You're welcome Nyholm ;)

**Pull request merged**
