### PR TITLE
Fix implicit nullable types to avoid PHP 8.4 warnings

### PR DESCRIPTION
**Pull request by eiriksm**

### CODE REVIEW

**Review by GrahamCampbell — CHANGES_REQUESTED** [review]
It's necessary to also run the CI on PHP 8.4.

**Comment by eiriksm** [comment]
> It's necessary to also run the CI on PHP 8.4.

Done

**Comment by GrahamCampbell** [comment]
Looks like there are more issues to fix. It may be easier to enable the php-cs-fixer rule that adds the `?` for you, to catch them all.

**Comment by eiriksm** [comment]
:+1: 

I am writing this on an airport before boarding my plane, so just mentioning that because I will get back to this :nerd_face:

**Comment by GrahamCampbell** [comment]
Looks like there are more downstream fixes that are needed first, to get this PR to pass.

**Comment by acrobat** [comment]
Thank you @eiriksm

**Comment by eiriksm** [comment]
Wow awesome thanks for the very fast response 

Would it also be possible to cut a new release with this included do you think? 🤓

**Comment by acrobat** [comment]
New release is created https://github.com/KnpLabs/php-github-api/releases/tag/v3.15.0

**Comment by eiriksm** [comment]
My gratitude is deep and sincere ♥️

Thanks for being an open source maintainer, and a great one at that 🚀

**Pull request merged**
