### PR TITLE
Repo::all method

### LINKED ISSUE #294: Listing all public repositories
https://developer.github.com/v3/repos/#list-all-public-repositories

I couldnt find how to get all public repositories?

### PR DESCRIPTION
**Pull request by Soullivaneuh**
Fixes #294.

### CODE REVIEW

**Comment by stof** [comment]
Should we really have the id argument there ? Shouldn't pagination be handled through the ResultPager instead ?

**Comment by Soullivaneuh** [comment]
I added this argument because GitHub permits it: https://developer.github.com/v3/repos/#list-all-public-repositories

I think it's still useful. For me, I use it for a long command that can start on the last checked id.

BTW, I follow the same method as [`User::all()`](https://github.com/KnpLabs/php-github-api/blob/d04c463835538250252bd84fe61dd10499879817/lib/Github/Api/User.php#L37-L43) does.

**Comment by stof** [comment]
OK, if there is already similar things elsewhere, fine.

this PR is missing tests and documentation though

**Comment by Soullivaneuh** [comment]
@stof Tests and documentation added.

**Pull request merged**
