### PR TITLE
Deployments: use proper media-type for in_progress/queued, inactive state

### PR DESCRIPTION
**Pull request by staabm**
closes https://github.com/KnpLabs/php-github-api/issues/978

### CODE REVIEW

**Review by acrobat — APPROVED** [review]

**Comment by acrobat** [comment]
Thank you @staabm

**Comment by staabm** [comment]
Thx for merging @acrobat .

Could this change also be merged into the 2.x branch?
Alternatively would you accept a Similar PR to the 2.x branch?

**Comment by acrobat** [comment]
Yes, this is a bugfix that could be backported! Can you create a PR for 2.x? Thanks!

**Comment by clxmstaab** [comment]
> Yes, this is a bugfix that could be backported! Can you create a PR for 2.x? Thanks!

here we go https://github.com/KnpLabs/php-github-api/pull/981

**Comment by clxmstaab** [comment]
@acrobat could we also get a new 3.x release? some bugfixes - like the one in this PR - are not yet part of a 3.x release, but are fixed on the latest 2.x releases

**Comment by acrobat** [comment]
@clxmstaab I will tag a new 3.x release today!

**Comment by acrobat** [comment]
@clxmstaab [3.2.0](https://github.com/KnpLabs/php-github-api/releases/tag/v3.2.0) is released!

**Comment by clxmstaab** [comment]
thank you so much 3

**Pull request merged**
