### PR TITLE
Add support for creating a repo dispatch event

### PR DESCRIPTION
**Pull request by Nyholm**
If you want to trigger a custom action, you need this API call.

### CODE REVIEW

**Comment by Nyholm** [comment]
Hm.. Im getting 404 back.. Not sure why,

**Comment by Nyholm** [comment]
No worries. 

I got a 404 instead of a 403. Everything is okey with this PR.

**Comment by acrobat** [comment]
Thank you @Nyholm

**Comment by Nyholm** [comment]
Thank you for merging.

**Pull request merged**
