### PR TITLE
Reduce code duplication and increase readability with NSA

### PR DESCRIPTION
**Pull request by Nyholm**
As mentioned in #446

Instead of using reflection, we could increase readability with the NSA lib.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Don't think it's worth adding a dependency for the sake of like 4 lines looking slightly different.

**Comment by Nyholm** [comment]
That is a fair point. But how many lines of code should one remove before we feel comfortable adding a **dev** dependency? Where is the magic limit? =)
screen shot 2016-10-20 at 10 54 52

**Comment by cursedcoder** [comment]
I think something like 5-10% of codebase should be at least?

**Comment by Nyholm** [comment]
We have 9105 lines of test code. I'll make the same PR again when it removes about 500 lines of code.

**Pull request closed without merging**
