### PR TITLE
Fix error in bc-check script

### LINKED ISSUE #841: Broken bc script
image

### PR DESCRIPTION
**Pull request by acrobat**
Fixes #841

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Do we even need this script anymore?

**Comment by acrobat** [comment]
Yes we need this to support both v1 and v2 of httplug. As the bc break tool thinks the interface changes on some of the httplug interfaces are bc breaks, but we have to bc layers in place so it's not a bc break for our users.

This script can be removed when we release a new major and remove support for httplug V1

**Comment by GrahamCampbell** [comment]
> Yes we need this to support both v1 and v2 of httplug. 

Not since the last release was tagged?

**Comment by acrobat** [comment]
@GrahamCampbell Hmm you could actually have a point there, let me check this! Otherwise we should indeed remove the script, no need for the extra complexity then.

**Pull request merged**
