### PR TITLE
feat: Secret Scanning Alerts

### LINKED ISSUE #1080: Secrets Scanning Alerts
Add Secrets Scanning Alerts for Entreprise, Organizations and Repository

https://docs.github.com/en/enterprise-server@3.5/rest/secret-scanning#list-secret-scanning-alerts-for-an-enterprise
call : Sprintf("enterprises/%v/secret-scanning/alerts", %enterprise)

https://docs.github.com/en/enterprise-server@3.5/rest/secret-scanning#list-secret-scanning-alerts-for-an-organization
call : Sprintf("orgs/%v/secret-scanning/alerts", %org)

https://docs.github.com/en/enterprise-server@3.5/rest/secret-scanning#list-secret-scanning-alerts-for-a-repository
call : Sprintf("repos/%v/%v/secret-scanning/alerts", owner, repo)

### PR DESCRIPTION
**Pull request by haridarshan**
Feature:

- Secret Scanning Alerts

Doc:
- Secret Scanning doc

Closes #1080

### CODE REVIEW

**Review by acrobat — CHANGES_REQUESTED** [review]
@haridarshan can you check and apply the failed styleci check? Otherwise the PR is ready to be merged!

**Review by acrobat — CHANGES_REQUESTED** [review]
@haridarshan can you check and apply the failed styleci check? Otherwise the PR is ready to be merged!

**Comment by haridarshan** [comment]
@acrobat :+1:

**Review by acrobat — APPROVED** [review]

**Comment by acrobat** [comment]
Thank you @haridarshan

**Pull request merged**
