### PR TITLE
Try to fix build in PHP 5.3

### PR DESCRIPTION
**Pull request by Nek-**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by Nek-** [comment]
@GrahamCampbell not awesome. Aggree. But this is the only way I see to continue support of PHP 5.3. (Otherwise it's time for new major release)

**Comment by GrahamCampbell** [comment]
You can support php 5.3 WITHOUT this change/

**Comment by stof** [comment]
there is a difference between supporting PHP 5.3 and running tests in the 5.3.3 version on Travis. The 5.3 environment has openssl properly. Only 5.3.3 does not.

I suggest simply removing 5.3.3 from the matrix, testing it only on an uptodate 5.3 version (as done for any other minor version of PHP)

**Comment by Nek-** [comment]
So this should be merge :) . Ping @stof

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by stof** [comment]
@Nek- I would say yes. The 5.3.3 image on Travis is simply not usable as it does not have openssl

**Pull request merged**
