### PR TITLE
Add Pagination in Search Repositories API

### PR DESCRIPTION
**Pull request by suresh-ramani**

### CODE REVIEW

**Review by v-porytskyi — APPROVED** [review]

**Comment by v-porytskyi** [comment]
Hi @suresh-ramani 
Are you planning to merge this anytime soon?

**Comment by suresh-ramani** [comment]
I have no access for merge this PR.

**Comment by GrahamCampbell** [comment]
This should not be merged. These parameters are intentionally not exposed. You need to use the result pager here, instead. https://github.com/KnpLabs/php-github-api/blob/master/doc/result_pager.md

**Comment by acrobat** [comment]
Yes indeed, as @GrahamCampbell said the result pager has full support for these parameters and there is no need to add them to indiviual api methods.

**Comment by GrahamCampbell** [comment]
People seem to make this error repeatedly. How can we help people reaching the wrong solution here?

**Pull request closed without merging**
