### PR TITLE
Add return fixer

### PR DESCRIPTION
**Pull request by Soullivaneuh**

### CODE REVIEW

**Comment by stof** [comment]
you may want to enable a few more rules too

**Comment by Soullivaneuh** [comment]
> you may want to enable a few more rules too

I agree, but I prefer @cursedcoder decision for that.

**Comment by cursedcoder** [comment]
you are right @Soullivaneuh,
if you mind add fixes for failing style-ci too

**Comment by GrahamCampbell** [comment]
You can download the diff StyleCI gives you and apply with with `git apply`. :)

**Comment by Soullivaneuh** [comment]
@cursedcoder It's done.

> You can download the diff StyleCI gives you and apply with with `git apply`. :)

You should add this tip on each analysis on your platform. ;-)

**Comment by GrahamCampbell** [comment]
Well, normally, you'd be able to have StyleCI create a PR, but it can't do that when the commit was made on a fork.

**Comment by Soullivaneuh** [comment]
> Well, normally, you'd be able to have StyleCI create a PR, but it can't do that when the commit was made on a fork.

So the tip has his place here. :-)

**Comment by GrahamCampbell** [comment]
Yeh. I guess. I'll add it at some point, lol. :)

**Pull request merged**
