### PR TITLE
Use the new cache plugin factory method

### LINKED ISSUE #502: Question about a problem with v. 2 cache - missing cache files
Hi

A v. 2.0.1 noob question:

In the v. 1.*  to use the cache I've used:

```php
$githubClient = new \Github\Client(
    new \Github\HttpClient\CachedHttpClient(['cache_dir' => storage_path('app/cache')])
);

$paginator = new \Github\ResultPager($githubClient);

// The rest of the code with requests
```

I see the cache files using this code, so I know they are created.

In the v. 2 I've tried the `php-cache/filesystem-adapter`:

```php
use League\Flysystem\Adapter\Local;
use League\Flysystem\Filesystem;
use Cache\Adapter\Filesystem\FilesystemCachePool;

// ...

$filesystemAdapter = new Local(storage_path('app')); // storage_path: laravel method pointing to "app" storage folder
$filesystem        = new Filesystem($filesystemAdapter);

$pool = new FilesystemCachePool($filesystem);

$client = new \Github\Client();
$client->addCache($pool);

$paginator = new \Github\ResultPager($client);

// The rest of the code with requests - exactly the same as for the 1.*
```

The end result is the same as in the v 1.* - that is, I'm successfully downloading a list of gists from github. During debugging I've checked that the cache plugin is added correctly.

The difference is - in the v. 2, with the code as seen above, no cache files are created. 

The path is correct, because a "cache" folder is created in laravel storage app folder - but it's empty.

I've tried also with `madewithlove/illuminate-psr-cache-bridge`. The code with it is somewhat different (the folder path is configured in laravel config), the end result is correct and without errors (I'm downloading a list of gists), but I don't see the cache files, they are not created.

What am I missing? Or how to debug it, any help with where to check what the problem is?

### PR DESCRIPTION
**Pull request by acrobat**
This pr updates the addCache method so we use the new factory method introduced in php-http/cache-plugin#26. This way the caching of github requests will work again. Fixes #502 

DO NOT MERGE! This can only be merged after a release of the php-http/cache-plugin (v1.3.0). But like you asked @Nyholm in [php-http/cache-plugin#26 (comment)](https://github.com/php-http/cache-plugin/pull/26#issuecomment-282699400)

### CODE REVIEW

**Comment by acrobat** [comment]
@Nyholm yes!

**Comment by Nyholm** [comment]
Good. Im just waiting on some input form Tuupola on the cache plugin. I'll make sure to tag it after I heard from him.

**Comment by acrobat** [comment]
That's good, thanks!

**Comment by acrobat** [comment]
:+1:  Fixed @Nyholm

**Comment by Nyholm** [comment]
Thank you @acrobat for your contributions!

**Comment by acrobat** [comment]
:tada: woohoo thanks!

**Pull request merged**
