### PR TITLE
phpunit update

### PR DESCRIPTION
**Pull request by kokspflanze**
removed unit test shouldNotUpdateHookWithoutName for https://github.com/KnpLabs/php-github-api/pull/442
`AbstractApiTest` cleanup with `ReflectionMethod`
`createMock` removed in ResultPagerTest like in https://github.com/KnpLabs/php-github-api/pull/438 comment written

### CODE REVIEW

**Comment by acrobat** [comment]
:+1: this should fix the tests! If the build is restarted it should pass as `php-http/client-common` 1.3 is released

**Comment by Nyholm** [comment]
Instead of duplicating the reflection code you could use the NSA lib: https://packagist.org/packages/nyholm/nsa

The code gets more readable with it.

**Comment by cursedcoder** [comment]
Can you please take care of conflicts?

**Comment by kokspflanze** [comment]
conflicts fixxed

about https://packagist.org/packages/nyholm/nsa it will be a new dependency, with just PHPUnit 4.0 support, which will be not realy helpful in both ways.

**Comment by cursedcoder** [comment]
Thank you!

**Comment by Nyholm** [comment]
Yes, NSA would be a new **dev** dependency. I know it is just a matter of taste but using NSA would remove about half the code you added here AND make it more readable. 

What **dev dependencies** NSA has does not matter for us. We would only care about the hard requirements for our dependencies. 

Anyhow, Good work with this PR. I'll make a new PR with NSA and we could discuss it there.

**Pull request merged**
