### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by verschoof**
Change to new way of adding composer packages

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by GrahamCampbell** [comment]
We should include both ways.

**Comment by verschoof** [comment]
We don't include both ways? I'm not sure If I get your point. I suggest to use  ONLY `Composer require` composer will search the correct version of the package for you.

**Comment by GrahamCampbell** [comment]
Not quite, `composer require` is massively overrated. It's possible that it could give you a version that conflicts with other dependencies. It doesn't actually check that.

**Comment by GrahamCampbell** [comment]
https://github.com/jeremeamia/super_closure#installation

**Comment by GrahamCampbell** [comment]
Can we just do something like that please?

**Comment by verschoof** [comment]
if you really want to a fixed version you can do:
`composer require knplabs/github-api:~1.4` (if i'm not mistaking) but this wont take the chance away of a conflict.

Can you also please put your messages in 1 message, this is not a chat box, Thanks

**Comment by GrahamCampbell** [comment]
I'm saying that we should retain a way that doesn't involve running the command, like I did on super closure.

> this is not a chat box

It pretty much is.

**Comment by jaspernbrouwer** [comment]
So I see 3 options:

1. `php composer.phar require knplabs/github-api`
2. `php composer.phar require knplabs/github-api:~1.4`
3. Edit `composer.json` manually and `php composer.phar update knplabs/github-api` (or `php composer.phar install`)

I can see that option 1 might fail, at which point you need to specify a version by using option 2 or 3.

I don't see why one would prefer option 3 (manually editing and still need to run a command) over option 2 (only run a command). Could you elaborate on that?

**Comment by GrahamCampbell** [comment]
> php composer.phar require knplabs/github-api

That's the best option. I'm not saying it isn't. I'm saying we should list BOTH versions like the repo I linked you to.

**Comment by jaspernbrouwer** [comment]
I'm arguing to use (both) option 1 and 2, not 1 and 3 :wink: (because 2 and 3 are effectively the same, 2 is less work)

**Comment by SakyaStelios** [comment]
The version is 1.5 now. This PR won't be merged?

**Comment by gquemener** [comment]
I'm :-1:, let's stick with composer update and not concern about upgrading the README everytime a new version is released. But thanks!

**Comment by jaspernbrouwer** [comment]
I don't get it :disappointed:

You say don't want to update the readme everytime a new (major/minor) version is released, but your solution is to keep mentioning version 1.4 even though that's not the latest stable anymore. IMHO this PR provides a better solution by not mentioning any version number at all.

**Pull request closed without merging**
