### PR TITLE
Add 'get milestones' for repo api

### PR DESCRIPTION
**Pull request by Jag96**
Gets the milestones for a repo: `$this->client->repo()->milestones($owner, $repo);`

### CODE REVIEW

**Comment by pilot** [comment]
make commits squash to remove duplication with the merge

**Comment by Jag96** [comment]
Squashed commits

**Comment by cursedcoder** [comment]
@Jag96 please rebase.

**Comment by Jag96** [comment]
Rebased

**Comment by cursedcoder** [comment]
thanks @Jag96

**Comment by Jag96** [comment]
Np!

**Pull request merged**
