### PR TITLE
Changed method name on list milestones

### PR DESCRIPTION
**Pull request by tmulry**

### CODE REVIEW

**Comment by m1guelpf** [comment]
Related issue: #573

**Comment by bobeagan** [comment]
This PR does not make any sense to me. 👎 
I think you misread the header. That example is showing how to list milestone **labels**.  See https://developer.github.com/v3/issues/labels/#get-labels-for-every-issue-in-a-milestone

**Comment by acrobat** [comment]
I'm also :-1: on this. @bobeagan is right, this method is used to list all labels for a milestone and [this method](https://github.com/KnpLabs/php-github-api/blob/master/doc/issue/milestones.md#list-milestones-for-a-repository) is used to list all milestones.
So the docs are correct

**Comment by tmulry** [comment]
@bobeagan 
You are right I misread the docs here.  Closing this one out.

**Pull request closed without merging**
