### PR TITLE
Remove BC check on 3.x

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Can be added back once 3.0.0 is tagged.

### CODE REVIEW

**Comment by acrobat** [comment]
Maybe it's better to set it as an allow_failure in travis until v3 is released. On the other hand we use a feature like Roave/BackwardCompatibilityCheck#81

**Comment by GrahamCampbell** [comment]
Maybe we could comment it out in the travis file, to try and make sure it's not forgotten about. That's what Guzzle did during Guzzle 7 development. Alternatively, I could always open a PR to revert this one marked as draft, so it's nor forgotten?

I'd be against setting to allow failure on the grounds that it's a waste of electricity to run the job.

**Comment by acrobat** [comment]
Comment it out in this PR and add a small comment above why it's commented and indeed open a draft PR to revert. I will set the milestone to 3.0 for that draft pr so we can revert it around/after the release!

**Comment by GrahamCampbell** [comment]
Done. :)

**Comment by GrahamCampbell** [comment]
Once this is merged, I'll rebase the PSR-17 PR, so we can see a passing build. 🎉

**Comment by acrobat** [comment]
Thank you @GrahamCampbell

**Pull request merged**
