### PR TITLE
Make sure we always use valid urls

### PR DESCRIPTION
**Pull request by Nyholm**
This is a massive PR but it does nothing but add a slash ("/") infront of all URL. 
The reason for this is because Guzzle decided to validate the url as soon as it changes. (https://github.com/guzzle/psr7/pull/94)

We added a url like "user/Nyholm/repos" then we use AddHostPlugin which executes like this: 

```php
$uri = $request->getUri()
                ->withHost($this->host->getHost())
                ->withScheme($this->host->getScheme())
                ->withPort($this->host->getPort())
            ;
```

If we add a host like "api.github.com" it will not be valid at that state. It was before because https://github.com/guzzle/psr7/pull/94/files#diff-db412dbd2c689be753da90d14beffc1bL461

With this PR we make sure to always have a valid URL. Because "/foo" is a valid URL.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Sad times...

image

**Comment by Nyholm** [comment]
Haha, On my way. 
I have to prepend the slash there as well.

**Comment by GrahamCampbell** [comment]
Yeh. :)

**Comment by Nyholm** [comment]
Thank you for merging.

**Pull request merged**
