### PR TITLE
Fix issue https://github.com/KnpLabs/php-github-api/issues/1061

### PR DESCRIPTION
**Pull request by mruell**

### CODE REVIEW

**Comment by acrobat** [comment]
I will take a look at this in the next few days and check if this changes doesn't break the current behaviour for github.com (latest) api's

**Review by acrobat — APPROVED** [review]

**Comment by acrobat** [comment]
Thank you @mruell

**Comment by acrobat** [comment]
Sorry for the delay @mruell! I've just released a new version which contains this fix!

**Comment by mruell** [comment]
Thank you very much! :)

**Pull request merged**
