### PR TITLE
Added support for getting star creation timestamps in activity/starring endpoint

### PR DESCRIPTION
**Pull request by antoniotajuelo**
Using special media type: Accept: application/vnd.github.v3.star+json

https://developer.github.com/v3/activity/starring/#list-stargazers

### CODE REVIEW

**Comment by acrobat** [comment]
Changes look good to me! Can you just add a small note in the docs about this configure method and when to call it. Thanks!

**Comment by antoniotajuelo** [comment]
Sure, let me do it.

**Comment by antoniotajuelo** [comment]
Done!

**Comment by acrobat** [comment]
Thanks @antoniotajuelo and congrats on your first contribution!

**Comment by antoniotajuelo** [comment]
No problem! I give a lot of usage to this library, so I am very happy to make contributions.

**Pull request merged**
