### PR TITLE
Don't urlencode integer values

### PR DESCRIPTION
**Pull request by acrobat**
Also some types have changed to string to be in line with the github api types

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Nice. 👍

**Comment by GrahamCampbell** [comment]
I wonder if we should add strict typing to all the files in 3.x?

**Comment by acrobat** [comment]
I think that could be a next step indeed. I'm preping a PR to set all docblocks correctly in the 2.x branch, which will allow us to use an automatic tool to convert these to typehints in v3.

**Comment by GrahamCampbell** [comment]
Could be risky if there are mistakes in the doc. I am in the process of doing something similar for the GitLab client https://github.com/m4tthumphrey/php-gitlab-api, however I won't add any scalar types to anything in the Api namespace for fear of breaking stuff. I will, however add strict typing everywhere, and scalar typehints everywhere else in that package. ;)

**Comment by acrobat** [comment]
Yes, that does mean that the docblocks should be correct. Something we can check but it's not a must for me, if we indeed have typehints in the other parts and enable strict typing it would a step forward!

**Comment by GrahamCampbell** [comment]
👍

**Pull request merged**
