### PR TITLE
Add support for branches API.

### PR DESCRIPTION
**Pull request by popcorn245**
Saw that all the code already existed. Just had to hook it up.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
What's with the comments?

**Comment by guillermoandrae** [comment]
Nice. Maybe a `branch` case, too?

Since there isn't any precedent for the kind of commenting @GrahamCampbell is referring to in your change, it seems out of place.

**Comment by popcorn245** [comment]
Sorry I used it as a way to tell what I changed when I look back on the
code. They are not by any means necessary. I will make the changes, branch
it, and submit another pull request. Thanks! ^_^

On Sat, Jan 10, 2015 at 10:44 AM, Guillermo A. Fisher <
notifications@github.com> wrote:

> Nice. Maybe a branch case, too?
>
> Since there isn't any precedent for the kind of commenting @GrahamCampbell
> <https://github.com/GrahamCampbell> is referring to in your change, it
> seems out of place.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KnpLabs/php-github-api/pull/224#issuecomment-69462124>
> .
>



-- 



Thanks,
     Bobby Johnson
     Cell: (314) 313-3351
     Email: Popcorn245@gmail.com

**Comment by stof** [comment]
This looks wrong. This API class is a subapi of the gitdata one. You should get it from there

**Comment by GrahamCampbell** [comment]
Yeh, this should be closed. Ping @pilot.

**Pull request closed without merging**
