### PR TITLE
Add an API to fetch the authenticated user.

### PR DESCRIPTION
**Pull request by greg-1-anderson**

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
**Workaround:**
```
        $response = $client->getHttpClient()->get('/user', []);
        $authenticated = ResponseMediator::getContent($response);
```

**Comment by acrobat** [comment]
@greg-1-anderson we already have a "current user" api endpoint, is this what you are looking for?

See: 
https://github.com/KnpLabs/php-github-api/blob/8ae8e86b70f2d44f560a75909b5622fc7d1489d6/lib/Github/Api/CurrentUser.php#L21..L24

**Comment by greg-1-anderson** [comment]
Ah, missed that API. Thanks.

**Comment by acrobat** [comment]
No problem, thanks for your effort!

**Pull request closed without merging**
