### PR TITLE
read api limit from response header

### PR DESCRIPTION
**Pull request by liaohuqiu**

### CODE REVIEW

**Comment by liaohuqiu** [comment]
According to https://developer.github.com/v3/#rate-limiting, we should read the api limit from the response header.

**Comment by liaohuqiu** [comment]
Did not pass the test, seems more work to do.

**Comment by stof** [comment]
Well, the test probably needs to be updated to reflect the logic change. You should reopen your PR IMO (and update it)

**Comment by liaohuqiu** [comment]
OK, I will try to update the test cases later.

**Comment by stof** [comment]
This fixes #211 btw

**Comment by cursedcoder** [comment]
done by #276

**Pull request closed without merging**
