### PR TITLE
Add params to collaborators api calls

### PR DESCRIPTION
**Pull request by convenient**
https://developer.github.com/v3/repos/collaborators/#list-collaborators
`GET /repos/:owner/:repo/collaborators`
Params = `affiliation`

https://developer.github.com/v3/repos/collaborators/#add-user-as-a-collaborator
`PUT /repos/:owner/:repo/collaborators/:username`
Params = `permission`

### CODE REVIEW

**Comment by convenient** [comment]
@Nyholm Just to confirm what you're wanting as there are currently no phpdoc function blocks.

```diff
+   /**
+    * @link https://developer.github.com/v3/repos/collaborators/#list-collaborators
+    *
+    * @param $username
+    * @param $repository
+    * @param array $params
+    * @return array|string
+    */
    public function all($username, $repository, array $params = [])
    {
        return $this->get('/repos/'.rawurlencode($username).'/'.rawurlencode($repository).'/collaborators', $params);
    }
```

Do you want me to add sections like that, or just the `@link`, or something else?

**Comment by Nyholm** [comment]
A block like that with the link will be perfect.

**Comment by convenient** [comment]
@Nyholm I added phpdoc to all functions within the class as it looked rather weird having only two of the functions doc'd.

**Comment by Nyholm** [comment]
Awesome. Thanks!

**Pull request merged**
