### PR TITLE
Change log for 2.12.0

### PR DESCRIPTION
**Pull request by Nyholm**
Prepare a new 2.12.0 release with HTTPlug 2.0 support!

### CODE REVIEW

**Comment by acrobat** [comment]
Thanks for preparing the release @Nyholm!

**Comment by acrobat** [comment]
I've published [2.12.0](https://github.com/KnpLabs/php-github-api/releases/tag/2.12.0)!

**Comment by OskarStark** [comment]
Woohoo 🎉

**Comment by Nyholm** [comment]
Awesome!

**Pull request merged**
