### PR TITLE
Added user suspension & un-suspension, resolves #207.

### PR DESCRIPTION
**Pull request by guillermoandrae**
@mdwheele I made changes similar to yours but added them to the User class.

### CODE REVIEW

**Comment by guillermoandrae** [comment]
@stof I moved the methods in hopes of getting this change approved sooner.

**Comment by guillermoandrae** [comment]
@pilot does this look good to you?

**Comment by guillermoandrae** [comment]
Anything else I need to do to this?

**Comment by guillermoandrae** [comment]
Can this be merged?

**Comment by guillermoandrae** [comment]
One more time... any issues with this?

**Comment by pilot** [comment]
https://github.com/KnpLabs/php-github-api/releases/tag/1.4.4

**Pull request merged**
