### PR TITLE
Renamed deploykeys class to reflect to github api name

### PR DESCRIPTION
**Pull request by acrobat**
The api for the current user is named public keys (in repo's it is deploykeys). So renamed the class for the current user to reflect the correct github api name

### CODE REVIEW

**Comment by cursedcoder** [comment]
Let's update changelog here then.

**Comment by acrobat** [comment]
Will do that later today!

**Comment by acrobat** [comment]
I've updated the changelog!

**Comment by cursedcoder** [comment]
Merge issues

**Comment by acrobat** [comment]
Fixed!

**Pull request merged**
