### PR TITLE
[3.x] Use RFC3986 for building URI query strings

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
The default is actually what's meant to be used to build request bodies, and not query strings. This is another blunder in the PHP naming of functions. RFC3986 is the (only) specification for query strings, and it should have been used always (though it only differs in a couple of edge cases, so people probably didn't notice things going wrong). :P

**Comment by acrobat** [comment]
That's clear, thanks for the explanation! 😄 Can you target the 2.x branch so we can already avoid these edge cases in v2!

**Comment by GrahamCampbell** [comment]
The reason I didn't originally target v2 was in case people had already worked around these edge cases themselves, and they find their work around break when we change the encoding. I can still send to 2.x if you want though. :)

**Comment by acrobat** [comment]
Thank you @GrahamCampbell

**Pull request merged**
