### PR TITLE
Apply fixes from StyleCI

### PR DESCRIPTION
**Pull request by acrobat**
This pull request applies code style fixes from an analysis carried out by [StyleCI](https://github.styleci.io).

---

For more information, click [here](https://github.styleci.io/analyses/YjOWdv).

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
?

**Comment by acrobat** [comment]
Huh, I didn’t close this 🤔 Let me check that tomorrow!

**Comment by GrahamCampbell** [comment]
Should be possible to re-open and merge from the GitHub UI.

**Comment by acrobat** [comment]
Yes I know, but I wanted to check if I could see why this was closed! Bu

**Pull request merged**
