### PR TITLE
Package guzzle/guzzle is abandoned

### PR DESCRIPTION
**Pull request by Gummibeer**
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks, but this isn't correct. The old package name is correct, the new one is only for v4+.

**Comment by GrahamCampbell** [comment]
We are using an abanonded package, yes.

**Comment by Gummibeer** [comment]
Ok, sorry - haven't checked this, just got the warning in composer.

**Comment by GrahamCampbell** [comment]
No worries. :)

We do have an open PR to address this in a radical way btw. ;)

**Pull request closed without merging**
