### PR TITLE
Add the ability to fetch user installations

### PR DESCRIPTION
**Pull request by bdelbasso**
It seems that this method is missing.

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you for this pr. I will close this however because this method already exists in Integrations::findInstallations

You may want to improve the documentation of this method so it easier can be found.

**Comment by bdelbasso** [comment]
Hi @Nyholm.

I don't understand why you are saying that this already exists. 

Integrations:findInstallations targets the following endpoint:
```
# Authorization header: JWT token of the integration
GET /integration/installations
```

While this PR targets:
```
# Authorization header: OAuth token of the user
GET /user/installations
```

I've tried a request on `/integrations/installations` with the OAuth token of a user, it returns a 401 Unauthorized "Invalid credentials".

Here is the [corresponding Github doc](https://developer.github.com/early-access/integrations/user-identification-authorization/#check-which-installations-resources-a-user-can-access).

**Comment by Nyholm** [comment]
You are correct. Im sorry. I must have reviewed this too quickly.

**Comment by acrobat** [comment]
@bdelbasso Can you also add support for the repositories endpoint? 

`/user/installations/:installation_id/repositories`. See https://developer.github.com/early-access/integrations/user-identification-authorization/#check-which-installations-resources-a-user-can-access

**Comment by Nyholm** [comment]
We need to add a `$params` parameter to support paging. See `CurrentUser::issues`. We do also need to add some tests. 

@acrobat: That is a great idea. But maybe that should be in a separate PR?

**Comment by acrobat** [comment]
I'm ok with a separate pr!

**Comment by bdelbasso** [comment]
@Nyholm @acrobat PR updated! Let's do the other endpoint in a separate PR when this one is complete.

**Pull request merged**
